name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger CI/CD when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger CI/CD on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Replace with the Node.js version you're using

    - name: Install dependencies
      run: npm install

    #- name: Run tests
     # run: npm test  # Ensure you have test scripts in your package.json

    #- name: Build the application
     # run: npm run build  # Adjust this to your build command

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /path/to/your/app
          git pull origin main  # Pull the latest changes
          npm install  # Install new dependencies
          pm2 restart your-app  # Restart your app with pm2
        EOF
      env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
