name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests (optional)
        run: echo "No tests specified"

      - name: Debug EC2 Public IP
        run: |
          echo "EC2 Public IP: ${{ secrets.EC2_PUBLIC_IP }}"

      - name: Save EC2 private key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > pem.pem
          chmod 600 pem.pem

      - name: Deploy to EC2
        run: |
          chmod 600 pem.pem
          ssh -o StrictHostKeyChecking=no -i pem.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/helloworld-node
            git pull --rebase origin main  # Resolve Git divergence
            npm install  # Install new dependencies
            # Check if server.js exists before starting the app
            if [ -f server.js ]; then
              pm2 restart app || pm2 start server.js --name app  # Restart your app with pm2
            else
              echo "server.js not found! Please check the repository."
              exit 1
            fi
          EOF

